version: "3"
services:
  client:
    build: .
    # ports:
    #   - 3006:80
    
  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=snowttt.duckdns.org
      - VALIDATION=duckdns
      - STAGING=false
    volumes:
      - /home/breanna/data/swag:/config
    ports:
    - 0.0.0.0:3006:443
    restart: unless-stopped